#!/bin/bash

CURDIR=$( cd "$( dirname "$0" )" && pwd );
MAINDIR=$( dirname "$CURDIR" )
echo -e "\033[0;32mBuild doc: $(readlink -f $MAINDIR) \033[0m";

# this file must be executed to regenerate the README.md
# upon binary internal documentation updates
# it requires the binary to be up to date and compiled

UNAME=`uname`

# the command 
CMD=""
if [ "$(uname)" == "Linux" ]; 
then
	CMD=${MAINDIR}/build/Release/bin/mm
else
	CMD=${MAINDIR}/build/Release/bin/Release/mm.exe
fi

if [ ! -f "$CMD" ]; then
	echo "Error: it requires the binary to be up to date and compiled (please execute ./build.sh )"
	exit
fi

echo -e \
	"\n\n<!--- \n" \
	"  ###################################################### \n" \
	"  # File automatically generated by ./doc/build-doc.sh # \n" \
	"  # sript and mm, do not edit manually.                # \n" \
	"  ###################################################### \n" \
	"--> \n\n" > ${MAINDIR}/README.md \

cat  ${MAINDIR}/doc/README.md >> ${MAINDIR}/README.md

echo -e "\n# Command references \n\`\`\`\n" >> ${MAINDIR}/README.md
${CMD} >> ${MAINDIR}/README.md
echo -e "\`\`\`\n\n" >> ${MAINDIR}/README.md

for cmd in analyse compare degrade dequantize normals quantize reindex render sample sequence
do 
	echo -e "## ${cmd^} \n\`\`\`\n" >> ${MAINDIR}/README.md	
	${CMD} ${cmd} >> ${MAINDIR}/README.md
	echo -e "\`\`\`\n\n" >> ${MAINDIR}/README.md
done

cat ${MAINDIR}/LICENSE.md >> ${MAINDIR}/README.md

# homogeneize line endings
dos2unix README.md
#EOF